/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import code.Customer;
import code.Bill;
import code.Book;
import code.BookManager;
import code.MainBill;
import code.ManageCustomer;
import code.ManageBookBill;
import code.ManageMainBill;

public class BillFrame extends javax.swing.JDialog {

    /**
     * Creates new form BillFrame
     */
    private BookManager bookManager = new BookManager();
    private ManageCustomer manageCustomer = new ManageCustomer();
    private ManageBookBill manageBookBill = new ManageBookBill();
    private Bill bill = new Bill();
    private MainBill mainBill = new MainBill();
    private ManageMainBill manageMainBill = new ManageMainBill();

    public BillFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        new Home().setVisible(false);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        loadBills();
        loadBooks();
        fillInBookTable();
        loadCustomers();
        setIdComboBox();
        clearBill();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        customersPanel1 = new javax.swing.JPanel();
        customersIDLabel = new javax.swing.JLabel();
        idComboBox = new javax.swing.JComboBox<>();
        backButton1 = new javax.swing.JButton();
        customersNameTextField = new javax.swing.JTextField();
        customersNameLabel = new javax.swing.JLabel();
        productsPanel = new javax.swing.JPanel();
        bookNameLabel = new javax.swing.JLabel();
        bookNameTextField = new javax.swing.JTextField();
        bookPriceLabel = new javax.swing.JLabel();
        bookPriceTextField = new javax.swing.JTextField();
        bookQuantityLabel = new javax.swing.JLabel();
        bookQuantityTextField = new javax.swing.JTextField();
        addBillButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billTxtArea = new javax.swing.JTextArea();
        bookListLabel2 = new javax.swing.JLabel();
        bookListPanel1 = new javax.swing.JPanel();
        bookListLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        productBillPanel = new javax.swing.JPanel();
        productsBillLabel = new javax.swing.JLabel();
        proBillTable = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        printButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        resetBillBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bill");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        customersPanel1.setBackground(new java.awt.Color(204, 204, 255));
        customersPanel1.setForeground(new java.awt.Color(190, 242, 229));

        customersIDLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        customersIDLabel.setForeground(new java.awt.Color(139, 139, 227));
        customersIDLabel.setText("ID:");

        idComboBox.setEditable(true);
        idComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idComboBoxItemStateChanged(evt);
            }
        });
        idComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idComboBoxMouseClicked(evt);
            }
        });
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        backButton1.setBackground(new java.awt.Color(153, 153, 255));
        backButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setText("Back");
        backButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        customersNameTextField.setEditable(false);
        customersNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersNameTextFieldActionPerformed(evt);
            }
        });

        customersNameLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        customersNameLabel.setForeground(new java.awt.Color(140, 140, 226));
        customersNameLabel.setText("Name:");

        javax.swing.GroupLayout customersPanel1Layout = new javax.swing.GroupLayout(customersPanel1);
        customersPanel1.setLayout(customersPanel1Layout);
        customersPanel1Layout.setHorizontalGroup(
            customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customersNameLabel)
                    .addComponent(customersIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customersNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        customersPanel1Layout.setVerticalGroup(
            customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customersIDLabel)
                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customersNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customersNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        productsPanel.setBackground(new java.awt.Color(204, 204, 255));

        bookNameLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bookNameLabel.setForeground(new java.awt.Color(139, 139, 224));
        bookNameLabel.setText("Book:");

        bookNameTextField.setEditable(false);
        bookNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameTextFieldActionPerformed(evt);
            }
        });

        bookPriceLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bookPriceLabel.setForeground(new java.awt.Color(139, 139, 224));
        bookPriceLabel.setText("Price:");

        bookPriceTextField.setEditable(false);
        bookPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPriceTextFieldActionPerformed(evt);
            }
        });

        bookQuantityLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bookQuantityLabel.setForeground(new java.awt.Color(139, 139, 224));
        bookQuantityLabel.setText("Quantity:");

        bookQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookQuantityTextFieldActionPerformed(evt);
            }
        });

        addBillButton.setBackground(new java.awt.Color(153, 153, 255));
        addBillButton.setFont(new java.awt.Font("VNI-Avo", 1, 18)); // NOI18N
        addBillButton.setForeground(new java.awt.Color(255, 255, 255));
        addBillButton.setText("Add");
        addBillButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBillButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(153, 153, 255));
        resetButton.setFont(new java.awt.Font("VNI-Avo", 1, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Clear");
        resetButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookQuantityLabel)
                    .addComponent(bookNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookNameTextField)
                    .addComponent(bookPriceTextField)
                    .addComponent(bookQuantityTextField)
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameLabel)
                    .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookQuantityLabel)
                    .addComponent(bookQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(addBillButton))
                .addGap(39, 39, 39))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        billTxtArea.setBackground(new java.awt.Color(232, 228, 228));
        billTxtArea.setColumns(20);
        billTxtArea.setRows(5);
        jScrollPane2.setViewportView(billTxtArea);

        bookListLabel2.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        bookListLabel2.setForeground(new java.awt.Color(138, 138, 219));
        bookListLabel2.setText("Bill");

        bookListPanel1.setBackground(new java.awt.Color(255, 255, 204));
        bookListPanel1.setForeground(new java.awt.Color(0, 204, 153));

        bookListLabel1.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        bookListLabel1.setForeground(new java.awt.Color(139, 139, 221));
        bookListLabel1.setText("Menu");

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Book", "Type", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);

        javax.swing.GroupLayout bookListPanel1Layout = new javax.swing.GroupLayout(bookListPanel1);
        bookListPanel1.setLayout(bookListPanel1Layout);
        bookListPanel1Layout.setHorizontalGroup(
            bookListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookListPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookListLabel1)
                .addGap(155, 155, 155))
        );
        bookListPanel1Layout.setVerticalGroup(
            bookListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookListPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookListLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(bookListPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookListLabel2)
                .addGap(170, 170, 170))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bookListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookListLabel2)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        productBillPanel.setBackground(new java.awt.Color(204, 204, 255));

        productsBillLabel.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        productsBillLabel.setForeground(new java.awt.Color(139, 139, 221));
        productsBillLabel.setText("Product Price");

        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proBillTable.setViewportView(billTable);

        printButton.setBackground(new java.awt.Color(153, 153, 255));
        printButton.setFont(new java.awt.Font("VNI-Avo", 1, 18)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setText("OK");
        printButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(153, 153, 255));
        removeButton.setFont(new java.awt.Font("VNI-Avo", 1, 18)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Delete");
        removeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        amountLabel.setBackground(new java.awt.Color(0, 153, 255));
        amountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        resetBillBtn.setBackground(new java.awt.Color(153, 153, 255));
        resetBillBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resetBillBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBillBtn.setText("Clear");
        resetBillBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBillBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productBillPanelLayout = new javax.swing.GroupLayout(productBillPanel);
        productBillPanel.setLayout(productBillPanelLayout);
        productBillPanelLayout.setHorizontalGroup(
            productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productBillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(productBillPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productBillPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(productBillPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(proBillTable, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBillPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productsBillLabel)
                .addGap(98, 98, 98))
        );
        productBillPanelLayout.setVerticalGroup(
            productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productBillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsBillLabel)
                .addGap(18, 18, 18)
                .addComponent(proBillTable, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetBillBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(productsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productBillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(productBillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -233;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customersNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersNameTextFieldActionPerformed
        showNameBill();
    }//GEN-LAST:event_customersNameTextFieldActionPerformed

    private void idComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idComboBoxItemStateChanged

    }//GEN-LAST:event_idComboBoxItemStateChanged

    private void idComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idComboBoxMouseClicked

    }//GEN-LAST:event_idComboBoxMouseClicked

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        showNameBill();
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void bookPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookPriceTextFieldActionPerformed

    private void addBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBillButtonActionPerformed
        int selectedRow = bookTable.getSelectedRow();
        if (selectedRow != -1) {
            try {
                int bookQuantity = Integer.parseInt(bookQuantityTextField.getText());
                fillInBillTable(selectedRow, bookQuantity);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid quantity.");
            }
        }
    }//GEN-LAST:event_addBillButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        bookNameTextField.setText("");
        bookPriceTextField.setText("");
        bookQuantityTextField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void bookNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameTextFieldActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        getDataFromTable();
    }//GEN-LAST:event_bookTableMouseClicked

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int selectedRow = billTable.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) billTable.getModel();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Select an item to remove.");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        fillInBill();
    }//GEN-LAST:event_printButtonActionPerformed

    private void resetBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBillBtnActionPerformed
        clearBill();
    }//GEN-LAST:event_resetBillBtnActionPerformed

    private void bookQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookQuantityTextFieldActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButton1ActionPerformed
    private void saveCustomers() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Customers.Dat"))) {
            oos.writeObject(manageCustomer.getListCustomer());
            //JOptionPane.showMessageDialog(this, "Customers saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving customers.");
        }
    }

    private void loadCustomers() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Customers.Dat"))) {
            manageCustomer.setListCustomer((ArrayList<Customer>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading customers.");
        }
    }

    public void saveBills() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Bills.dat"))) {
            oos.writeObject(manageMainBill.getListMainBills());
            JOptionPane.showMessageDialog(this, "Bills saved!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving to file: " + e.getMessage());
        }
    }

    public void loadBills() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Bills.dat"))) {
            manageMainBill.setListMainBills((ArrayList<MainBill>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading.");
        }
    }

    public void saveBooks() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Books.dat"))) {
            oos.writeObject(bookManager.getBookList()); // Save only the ArrayList<CD>
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving to file: " + e.getMessage());
        }
    }

    public void loadBooks() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Books.dat"))) {
            bookManager.setBookList((ArrayList<Book>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading Books from file.");
        }
    }

    private void fillInBookTable() {
        DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
        int rowCount = model.getRowCount();
        // Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        // Add rows from the student list to the table model
        for (Book fi : bookManager.getBookList()) {
            Object[] row = new Object[]{
                fi.getBookId(),
                fi.getBookName(),
                fi.getBookType(),
                fi.getPrice()
            };
            model.addRow(row);
        }
        pack();
    }

    public void showNameBill() {
        String id = String.valueOf(idComboBox.getSelectedItem());
        Customer cus = manageCustomer.findCustomer(id);
        if (cus != null) {
            customersNameTextField.setText(cus.getCustomerName());
        } else {
            customersNameTextField.setText("");
        }
    }

    public void setIdComboBox() {
        idComboBox.removeAllItems();
        for (Customer cus : manageCustomer.getListCustomer()) {
            idComboBox.addItem(String.valueOf(cus.getCustomerID()));
        }
    }

    private void getDataFromTable() {
        int selectedRow = bookTable.getSelectedRow();
        if (selectedRow != -1) {
            Book fi = bookManager.getBookList().get(selectedRow);

            bookNameTextField.setText(fi.getBookName());
            bookPriceTextField.setText(String.valueOf(fi.getPrice()));

            bookNameTextField.setEditable(false);
            bookPriceTextField.setEditable(false);
        }
    }

    private void fillInBillTable(int selectedRow, int bookQuantity) {
        Book fi = bookManager.getBookList().get(selectedRow);
        String bookName = fi.getBookName();
        double bookPrice = fi.getPrice();
        double totalPrice;

        if (bookQuantity <= 0 || bookQuantity > fi.getQuantity()) {
            JOptionPane.showMessageDialog(this, "Only " + fi.getQuantity() + "book(s) left");
            return;
        }

        totalPrice = bookPrice * bookQuantity;

        Bill fooBi = new Bill(bookName, bookPrice, bookQuantity, totalPrice);
        manageBookBill.getBills().add(fooBi);

        // Trừ và cập nhật BookManager
        fi.setQuantity(fi.getQuantity() - bookQuantity);
        saveBooks();

        // Thêm vào bảng hóa đơn
        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.addRow(new Object[]{bookName, bookPrice, bookQuantity, totalPrice});
    }

    public void fillInBill() {
        try {
            DecimalFormat df = new DecimalFormat("#,##0.00");
            LocalDateTime dateTime = LocalDateTime.now();
            String customerId = idComboBox.getSelectedItem().toString();
            String customerName = customersNameTextField.getText();
            ArrayList<Bill> items = manageBookBill.getBills();
            float grandTotal = 0;

            for (Bill item : items) {
                grandTotal += item.getTotalPrice();
            }

            MainBill mBill = new MainBill(dateTime, customerId, customerName, items, grandTotal);

            String billText = mBill.generateBillText(df);
            billTxtArea.setText(billText);

            manageMainBill.getListMainBills().add(mBill);

            saveBills();

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "An error occurred due to null data: " + e.getMessage(), "Data Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearBill() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String header = "\t" + dateFormat.format(date) + "\n"
                + "Book Name\tQuantity\tPrice\tTotal Price\n"
                + "-------------------------------------------------------------------------------------\n";

        billTxtArea.setText(header);

        customersNameTextField.setText("");
        idComboBox.setSelectedIndex(-1);

        manageBookBill.getBills().clear();

        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.setRowCount(0);
    }
    

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBillButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton backButton1;
    private javax.swing.JTable billTable;
    private javax.swing.JTextArea billTxtArea;
    private javax.swing.JLabel bookListLabel1;
    private javax.swing.JLabel bookListLabel2;
    private javax.swing.JPanel bookListPanel1;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JLabel bookPriceLabel;
    private javax.swing.JTextField bookPriceTextField;
    private javax.swing.JLabel bookQuantityLabel;
    private javax.swing.JTextField bookQuantityTextField;
    private javax.swing.JTable bookTable;
    private javax.swing.JLabel customersIDLabel;
    private javax.swing.JLabel customersNameLabel;
    private javax.swing.JTextField customersNameTextField;
    private javax.swing.JPanel customersPanel1;
    private javax.swing.JComboBox<String> idComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton printButton;
    private javax.swing.JScrollPane proBillTable;
    private javax.swing.JPanel productBillPanel;
    private javax.swing.JLabel productsBillLabel;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton resetBillBtn;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

}
