/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import code.ManageUser;
import code.User;

public class Signup extends javax.swing.JFrame {

    private ManageUser manageOwner ;

    public Signup(ManageUser manageOwner) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);

        this.manageOwner = manageOwner;
        loadOwners();
    }

    private void loadOwners() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("User.Dat"))) {
            manageOwner.setListUser((ArrayList<User>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading owners.");
        }
    }

    private void saveOwners() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("User.Dat"))) {
            oos.writeObject(manageOwner.getListUser());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving customers.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean checkUsername() {
        for (User owner : manageOwner.getListUser()) {
            if (owner.getUsername().equals(usernameTF.getText())) {
                return true;
            }
        }
        return false;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        welcomeLabel1 = new javax.swing.JLabel();
        welcomeLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        signinIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        passwordTF = new javax.swing.JPasswordField();
        rewriteTF = new javax.swing.JPasswordField();
        showRBT = new javax.swing.JRadioButton();
        registerBT = new javax.swing.JButton();
        usernameTF = new javax.swing.JTextField();
        createLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        repasswordLabel = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(181, 181, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome Back");
        jPanel2.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 17, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________________________");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 65, -1, -1));

        welcomeLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        welcomeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel1.setText("To keep connected with us please");
        jPanel2.add(welcomeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 114, -1, -1));

        welcomeLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        welcomeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel2.setText("Log in with your personal info");
        jPanel2.add(welcomeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 154, -1, 23));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        signinIcon.setForeground(new java.awt.Color(181, 181, 246));
        jPanel2.add(signinIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 195, -1, 138));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 150, 150));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(227, 220, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 270, -1));
        jPanel1.add(rewriteTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 270, -1));

        showRBT.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        showRBT.setForeground(new java.awt.Color(139, 139, 221));
        showRBT.setText("Show/hide password");
        showRBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRBTActionPerformed(evt);
            }
        });
        jPanel1.add(showRBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 170, -1));

        registerBT.setBackground(new java.awt.Color(153, 153, 255));
        registerBT.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        registerBT.setForeground(new java.awt.Color(255, 255, 255));
        registerBT.setText("Sign Up");
        registerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTActionPerformed(evt);
            }
        });
        jPanel1.add(registerBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, 36));
        jPanel1.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 270, -1));

        createLabel.setBackground(new java.awt.Color(255, 255, 255));
        createLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        createLabel.setForeground(new java.awt.Color(153, 153, 255));
        createLabel.setText("Sign Up");
        jPanel1.add(createLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("___________________________________________________________________________");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 62, 390, -1));

        usernameLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(139, 139, 221));
        usernameLabel.setText("Username:");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 85, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(139, 139, 221));
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 85, -1));

        repasswordLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        repasswordLabel.setForeground(new java.awt.Color(139, 139, 221));
        repasswordLabel.setText("Confirm Password:");
        jPanel1.add(repasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        backBT.setBackground(new java.awt.Color(153, 153, 255));
        backBT.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        backBT.setForeground(new java.awt.Color(255, 255, 255));
        backBT.setText("Login");
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        jPanel1.add(backBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 150, 36));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        jPanel3.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 12);
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backBTActionPerformed

    private void registerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTActionPerformed
        if (usernameTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter username!");
            usernameTF.requestFocus();
            return;
        } else if (usernameTF.getText().contains(" ")) {
            JOptionPane.showMessageDialog(this, "Invalid username");
            usernameTF.requestFocus();
            return;
        } else if (passwordTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter password.");
            passwordTF.requestFocus();
            return;
        } else if (rewriteTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please confirm password.");
            rewriteTF.requestFocus();
            return;
        }
        
        if(!(new String(passwordTF.getPassword()).equals(new String(rewriteTF.getPassword())))) {
            JOptionPane.showMessageDialog(this, "Your password does not match!");
        } else {
            String username = usernameTF.getText();
            String password = passwordTF.getText();

            User owner = new User(username, password);

            if (manageOwner.searchUsername(username)) {
                manageOwner.getListUser().add(owner);
                JOptionPane.showMessageDialog(this, "New user has been added.");
                saveOwners();
                clearButton();
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Username is used.");
                return;
            }
        }
    }//GEN-LAST:event_registerBTActionPerformed

    private void showRBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRBTActionPerformed
        if (showRBT.isSelected()) {
            passwordTF.setEchoChar((char) 0);
            rewriteTF.setEchoChar((char) 0);
        } else {
            passwordTF.setEchoChar('*');
            rewriteTF.setEchoChar('*');
        }
    }//GEN-LAST:event_showRBTActionPerformed
    private void clearButton() {
        usernameTF.setText("");
        passwordTF.setText("");
        rewriteTF.setText("");
        showRBT.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    private javax.swing.JLabel createLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton registerBT;
    private javax.swing.JLabel repasswordLabel;
    private javax.swing.JPasswordField rewriteTF;
    private javax.swing.JRadioButton showRBT;
    private javax.swing.JLabel signinIcon;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel1;
    private javax.swing.JLabel welcomeLabel2;
    // End of variables declaration//GEN-END:variables
}
